#!/bin/bash

# WhatsApp Business API Setup Script for MoltWorker

set -e

echo "📱 WhatsApp Business API Setup"
echo "=============================="
echo ""

echo "Step 1: Meta Developer Account"
echo "-----------------------------"
echo "1. Go to: https://developers.facebook.com/"
echo "2. Create developer account (if not already)"
echo "3. Create new app → Select 'Business' type"
echo "4. App name: 'Moltbot WhatsApp'"
echo ""

echo "Step 2: Add WhatsApp Product"
echo "---------------------------"
echo "1. In app dashboard, click 'Add Product'"
echo "2. Find 'WhatsApp' → Click 'Set Up'"
echo "3. You'll see:"
echo "   - Phone Number ID"
echo "   - WhatsApp Business Account ID"
echo "   - Access Token (click 'Generate' if needed)"
echo ""

echo "Step 3: Generate Webhook Token"
echo "-----------------------------"
WEBHOOK_TOKEN=$(openssl rand -base64 32 | tr -d '=+/' | head -c 32)
echo "Your Webhook Verify Token: $WEBHOOK_TOKEN"
echo "SAVE THIS TOKEN!"
echo ""

echo "Step 4: Configure Webhook in Meta"
echo "--------------------------------"
echo "1. Go to 'WhatsApp' → 'Configuration' → 'Webhooks'"
echo "2. Click 'Edit' on Callback URL"
echo "3. Enter:"
echo "   - Callback URL: https://moltbot-sandbox.yksanjo.workers.dev/api/whatsapp"
echo "   - Verify Token: $WEBHOOK_TOKEN"
echo "4. Subscribe to fields:"
echo "   - messages"
echo "   - message_template_status_update"
echo ""

echo "Step 5: Add Phone Number"
echo "-----------------------"
echo "1. Go to 'WhatsApp' → 'API Setup'"
echo "2. Click 'Add Phone Number'"
echo "3. You need a dedicated phone number for WhatsApp Business"
echo "4. Verify via SMS/call"
echo ""

echo "Step 6: Set WhatsApp Secrets in Cloudflare"
echo "-----------------------------------------"
echo "Run these commands after getting your credentials:"
echo ""
echo "# WhatsApp Business API Token"
echo "echo 'YOUR_WHATSAPP_TOKEN' | npx wrangler secret put WHATSAPP_BUSINESS_TOKEN"
echo ""
echo "# Phone Number ID"
echo "echo 'YOUR_PHONE_NUMBER_ID' | npx wrangler secret put WHATSAPP_PHONE_NUMBER_ID"
echo ""
echo "# Business Account ID"
echo "echo 'YOUR_BUSINESS_ACCOUNT_ID' | npx wrangler secret put WHATSAPP_BUSINESS_ACCOUNT_ID"
echo ""
echo "# Webhook Verify Token"
echo "echo '$WEBHOOK_TOKEN' | npx wrangler secret put WHATSAPP_WEBHOOK_TOKEN"
echo ""

echo "Step 7: Redeploy MoltWorker"
echo "--------------------------"
echo "After setting all secrets, redeploy:"
echo "npm run deploy"
echo ""

echo "Step 8: Test Integration"
echo "----------------------"
echo "1. Send a message to your WhatsApp Business number"
echo "2. Check Cloudflare Worker logs:"
echo "   npx wrangler tail moltbot-sandbox"
echo "3. You should see webhook events and responses"
echo ""

echo "📋 Notes:"
echo "- First 1,000 messages/day are free"
echo "- Need approved message templates for proactive messages"
echo "- Template approval takes 24-48 hours"
echo "- Webhook verification happens immediately after setup"
echo ""

echo "✅ WhatsApp integration ready to set up!"